name: slimmersworld
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.3
  google_sign_in: ^6.3.0
  http: ^1.4.0
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  image_picker: ^1.1.2
  google_fonts: ^6.2.1
  url_launcher: ^6.3.1
  app_links: ^6.4.0
  webview_flutter: ^4.13.0
  table_calendar: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/

flutter_icons:
  android: true
  ios: true
  image_path: "images/logo_image.png"
